name: Update Visitors Count

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Update README
        run: |
          sudo apt-get install -y jq
          VISITORS_COUNT=$(curl -s "https://api.github.com/repos/amirallami-code/amirallami-code/traffic/views" | jq '.count')
          sed -i 's/visitors: "[^"]*"/visitors: "'$VISITORS_COUNT'"/' README.md
          cat README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update visitors count to $VISITORS_COUNT"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
