name: Update Visitors Count

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update README
      run: |
        VISITORS_COUNT=$(curl -s "https://profile-counter.glitch.me/amirallami-code/count.svg" | grep -oP '(?<=<text[^>]*>)[^<]+' | head -1)
        echo "Visitors count: $VISITORS_COUNT"
        sed -i "s/Visitors: [0-9]*/Visitors: $VISITORS_COUNT/" README.md
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md
        git commit -m "Update visitors count to $VISITORS_COUNT" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
